[package]
name = "ffxiv-tracker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "ffxiv-tracker"
test = false

[dependencies]
insta = "1.39.0"
scraper = "0.19.0"
strum = { version = "0.26.2", features = ["derive"] }
thiserror = "1.0.61"
ureq = "2.9.7"
