[package]
name = "ffxiv-tracker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "ffxiv-tracker"
test = false

[dependencies]
parse-display = "0.9.1"
scraper = "0.19.0"
thiserror = "1.0.61"
ureq = "2.9.7"
